

# Spring Configuration
spring:
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerceBackend
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver





  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update  # Be careful with this in production
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect



  # Security Configuration
  security:
    user:
      name: admin
      password: admin  # This is temporary, we'll change it later